### ISSUE TITLE
Explanation on how to use Slack

### ISSUE THREAD

**Issue by wuworkshop** [codebuddiesdotorg/codebuddies#14]
An explanation of how to use Slack -- e.g. recommend downloading the slack app so one can join other Slack communities as well without having to switch, short explanation of the 88 channels, highlights of some channels such as

**Comment by Luxisapex** [comment]
I intended to prototype this feature but I'm not used to the Meteor ecosystem yet.

Do we have a standard for working with multiple pages? Found this Stackoverflow answer which seems relevant, though possibly outdated:

http://stackoverflow.com/questions/26944011/proper-way-to-handle-multiple-pages-in-meteor

**Comment by wuworkshop** [comment]
Linking to this Slack tour would be good for more visual learners:

https://codebuddiesmeet.slack.com/getting-started

**Comment by wuworkshop** [comment]
This is a bit more specific to CB, but the "how to use Slack" page should stress that Slack is more asynchronous communication. Also, it's an international community, so members shouldn't expect an immediate reply when they need help with some code problem or something. But they should feel free to post their code and someone might post a reply later.

**Comment by adachiu** [comment]
@wuworkshop has a great point on "members shouldn't expect an immediate reply when they need help"
@lpatmo we should reword the copy on the home page so it doesn't set any false expectations. Currently it's "Need help or want to chat about code?" 

Instead of having a "how to use slack" page, we could have the slackbot message the new user with a brief intro to the channels available and reiterate that the community helps each other through asynchronous communication. The home page already has a link to learn more about Slack itself, so I think it's enough.
