### ISSUE TITLE
IDEA: Home(Dashboard) Redesign using CSS Cards

### ISSUE THREAD

**Issue by sergeant-q** [codebuddiesdotorg/codebuddies#203]
I am opening this up for feedback and suggestions but it's an idea. The current design of the two column grid with the hangouts listed on the left hand side seems a bit difficult to consume and discover.

I am proposing a redesign that incorporates a "**card-based**" design. Below is an example for inspiration:

![google now card design](http://thenextweb.com/wp-content/blogs.dir/1/files/2015/06/Screen-Shot-2015-06-16-at-08.57.56.png)
### Another example:

https://dribbble.com/shots/1475597-Mail-Client-UI-Concept/attachments/220136
### Benefits
- Easier to view/discover hangouts
- Appealing and better UX
- Mobile friendly

**Comment by lpatmo** [comment]
Agreed! The home page looks better with a narrower sidebar (8-4 instead of 7-5 grid), and having cards will ensure that a user can see more about what's going on without having to scroll.

I need to mock up where the date should go on each card (maybe at the top).

**Comment by adachiu** [comment]
I like the idea! Here's a mock of the card layout for discussion. The sidebar's main state could be focused on **1) I'm working on** and **2) Today I learned** ... when you click on the arrow, it shifts the sidebar state to show either "# people are online learning" or "# accomplishments"

This way we can keep the home dash less crowded with information and focus on the higher priority features.

The cards would need a "Join" button as well (maybe at the top right corner or on a hover state).

The ongoing hangout cards could have "ongoing" at the top right corner.. or maybe a hover state like the "Completed" and "Cancelled" overlays.

![home-dash-card-v1 0](https://cloud.githubusercontent.com/assets/13413986/18737201/94559b9c-8043-11e6-9d4f-c0e0b1297eaa.jpg)

![home-dash-card-v1 1](https://cloud.githubusercontent.com/assets/13413986/18737204/992c0714-8043-11e6-9361-42bfe1f8e2de.jpg)

![home-dash-card-v1 2](https://cloud.githubusercontent.com/assets/13413986/18737211/a17a88fa-8043-11e6-8dcb-dae33174c490.jpg)

**Comment by anbuselvan** [comment]
Awesome @adachiu.

**Comment by adachiu** [comment]
@lpatmo For the number count of accomplishments, is it not a daily count? On the live site right now, it's showing the total amount of accomplishments since it started so the number of accomplishments would just keep on increasing. Did we want to consider maybe capping it at weekly or even monthly accomplishments?

**Comment by lpatmo** [comment]
It looks brilliant, Ada!!

Yeah, the number of accomplishments is a global count. I think it would be nice to see the total number of accomplishments the community has completed, but a weekly/monthly would certainly be more helpfull. :) (And in the future we can sort people into houses! And people can earn points for their house!!! /harrypotter hat)

@adachiu A quick note on the categories -- @distalx was thinking of letting people use #hashtags in the hangout titles, e.g. #javascript hangout to learn X. 

Maybe instead of the tags at the very top, the "Upcoming in X minutes" or "Join Hangout" buttons could be there?

And I assume the following is true:
- When a user hovers over a card, they see the description
- They'll be able to click on a button at the top of the card to RSVP or un-RSVP to the hangout.

**Comment by lpatmo** [comment]
I'm probably going to start another 4-hour long hangout sometime this weekend to start and hopefully complete this issue.

**Comment by adachiu** [comment]
@lpatmo We discussed this mock on Slack previously. Posting here to get help on building this. Also we could continue discussing it.

Recap:
The `hangout cards` would have a hover state where the hangout details are shown. The user will be able to do the following on the hover state:

- Click on a `join` button
- Click on a `leave` button (if they already joined)
- Click on the `expand` icon to view the `single hangout post page` where they can write comments and see who has joined the hangout.

![home-dash-card-v1 3](https://cloud.githubusercontent.com/assets/13413986/19408055/bd05c4ae-9268-11e6-963e-b24ccc9c4506.jpg)

**Comment by lpatmo** [comment]
Update: @abhiii5459 and I have been working on this issue in the `issue-203` branch. Feel free to check it out. I still have to finish the hover effect and turn the "leave" link into a button, but it's on its way. The right-hand UI might become its own issue.
