### ISSUE TITLE
Google Hangout API alternatives

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#364]
The context: When you create a new post on codebuddies.org, you'll see a "Start the hangout" button that you can click on to launch a new Google Hangout. And when the time of the hangout arrives, others will be able to click on a "Join" button to join this Google Hangout. In the background, we're using the Google Hangout API to remember the link of the hangout that was generated (a link that looks similar to https://talkgadget.google.com/hangouts/_/a37oujy42rhglfnwksm6fznafae?hl=en) and pushing that via a PUT request to the codebuddies.org website, where we save it in the schema for one of the hangout posts.

The problem: Google Hangout is sometimes not very reliable. There was the case of a broken API in July, and occasionally we'll see errors like this:

![screen shot 2016-10-24 at 9 12 34 pm](https://cloud.githubusercontent.com/assets/4512699/19673554/c0c6bb64-9a35-11e6-8f39-460b80f457f9.jpg)

Some alternatives:
• https://talky.io/
• https://zoom.us/ 
• https://appear.in/ 

(H/T @dallas for the summary.)

• https://talky.io/ (recommended b y @dallas)
Advantages: `they allow for more than 8 people (as is the case with appear.in) and for longer sessions than 40 minutes (as is the case with Zoom) in their free tier.` - @dallas 
Disadvantages: no apparent API, though maybe we can talk to them more to find out more about `TalkyCore`. And there would be a fee involved.

• https://zoom.us/ (suggested by @sergeant-q)
Advantages: High-quality.
Disadvantages: Participants all have to download a plugin to their desktop in order to join. Maybe clunky interface?

• https://appear.in/ 
Advantages: There's an API! Can default-launch hangouts with no video call. Also, we can embed appear.in directly onto the page. (But screensharing is only available in the pop-up version.)
Disadvantages: Need to test out microphone and multi-screensharing, which was iffy when we tested a couple of months ago.

**Comment by wuworkshop** [comment]
Another possible alternative - https://www.uberconference.com/

**Comment by foxiae** [comment]
Hadn't @distalx mentioned something that was open source awhile back?

**Comment by distalx** [comment]
Thanks for reminder, I had suggest use of [jitsi-meet](https://github.com/jitsi/jitsi-meet).
AFAIK Rocket chat uses it.

**Comment by sergeant-q** [comment]
I really like the idea of leveraging an API. However, I still think **_appear.in_** has a few kinks with Chrome with audio working intermittently. It seems to work well with FireFox. It is also important to note that this is a peer-to-peer service, so audio/video performance can be hindered if anyone has a poor connection or low bandwidth.  Lastly, it seems that it will also require you to install a browser extension to do screen sharing. 

@distalx **_jitsi-meet_** looks interesting and is nice that it's open sourced.  However, the implementation is not straightforward and will require hosting it ourselves.  Plus the administration can be a pain.  

@wuworkshop my thoughts on **_uberconference_** is that with the free plan, it requires someone to enter a PIN to access the room.  This hinders the UX for users looking to easily join a hangout. The process won't be as smooth. 

I had suggested **_zoom.us_** because of the high quality. They do have an API but I believe it requires a user account registered to even access it to create meetings. So this would mean, we'd need to create a global CB account or something like that and test it out.  As @lpatmo noted - it does require a client download/installation which is not entirely the smoothest process either. 

**My thoughts are to retest appear.in and do a prototype implementation and test the heck out of it. It's free (though with some minor limitations) and a very straight forward API that we can install via NPM!**

**Comment by wuworkshop** [comment]
@sergeant-q hmm.. is that for people who have to dial by phone? TBH, I've only used Uberconference in a web browser which was quite easy. I just go the conference url and just click a button to enter a conference call. I think for screen-sharing, you have to install their Chrome extension or something.

**Comment by sergeant-q** [comment]
@wuworkshop I confirmed and it is for dial-in. So that piece is not critical. I researched if UberConferenced offered an API and it [does](https://www.uberconference.com/developers). However, firstly, it is in closed beta and secondly, it requires each organizer to have a registered account. I am not sure if that's feasible for what we want.

**Comment by lpatmo** [comment]
@distalx, @BethanyG and I tested out audio and screensharing with jitsi.org, and it seemed to work really well. It's open-sourced and designed very much like Google Hangout, so it felt easy to use:

![screen shot 2017-01-18 at 9 54 40 pm](https://cloud.githubusercontent.com/assets/4512699/22096220/f9f16ff6-ddce-11e6-8e3b-79fd2d0c12cb.jpg)

**Comment by lpatmo** [comment]
Very easy to embed: https://jsfiddle.net/1vq278cj/

**Comment by lpatmo** [comment]
Wow, this thread! :) We've successfully implemented Jitsi and have been using it for a couple of months, now, so am closing.
