### ISSUE TITLE
10 minutes before a hangout starts, send a Slack alert reminder to all the RSVPers of a hangout

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#417]
We already have a 2-hour Slack hangout reminder that goes to the #general channel (or #cb2-test, if on localhost:3000). 

Many people don't follow the #general channel, however. And they'll forget about the 24-hour reminder sent out via email.

We should ping all the attendees of the hangout 10 minutes before the hangout on Slack. The message could say something like:

```Hi @username! This is a reminder that you've RSVPed to [CodeBuddies hangout post]. Please join when it starts in 5 minutes, or let the host, @username2, know that you won't be able to make it.```

**Comment by nehalita** [comment]
didn't have time to commit but here are my findings:

in [cron_job/methods.js](https://github.com/codebuddiesdotorg/cb-v2-scratch/blob/master/server/cron_job/methods.js):
 - need to change [time_diff](https://github.com/codebuddiesdotorg/cb-v2-scratch/blob/master/server/cron_job/methods.js#L21) variable (it's an integer representing hours right now so you can't detect if it's within 10 minutes)
 - will likely add else if block to detect within 10 minutes [around here](https://github.com/codebuddiesdotorg/cb-v2-scratch/blob/master/server/cron_job/methods.js#L44) (~0.167 hours) and could call `slackNotification(hangout, "REMINDER")` or create new type like `slackNotification(hangout, "10 MINUTE REMINDER")` depending on approach

in [slack/methods.js](https://github.com/codebuddiesdotorg/cb-v2-scratch/blob/master/server/slack/methods.js):
 - major thing is that we need to create a separate method to message individual users on slack. Will need to iterate through users for the hangout and message from `Meteor.settings.slack_alert_username`. Won't be able to use [hangoutAlert variable](https://github.com/codebuddiesdotorg/cb-v2-scratch/blob/master/server/slack/methods.js#L11) because that only messages to a certain channel

**Comment by BethanyG** [comment]
This may be the same thing, but I found this interesting - you can set /remind in Slack for other users - and it can be done with a timestamp - so it could be set at the time a user RSVP'd to a hangout, theoretically:  https://api.slack.com/methods/reminders.add instead of setting an slackNotification.

**Comment by lpatmo** [comment]
I think we can close this issue, since users now get a 2-hour Slack @mention in the #announcements channel if they've RSVPed to a hangout.

Users are also likely to check email, so in the future, we'll have an email reminder notification. This feature has been noted in https://github.com/codebuddiesdotorg/codebuddies/projects and I will file an individual bug for it soon.

Thanks @nehalita and @BethanyG for thinking about this issue!
