### ISSUE TITLE
Fix logo in CB hangout reminder email

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#428]
![screen shot 2016-11-20 at 10 41 23 am](https://cloud.githubusercontent.com/assets/4512699/20465253/036a0ede-af0e-11e6-9864-c95ee9f99f1d.jpg)

**Comment by anish-shekhawat** [comment]
I would like to give it a try!

**Comment by wuworkshop** [comment]
it's all yours @anish-shekhawat

**Comment by anish-shekhawat** [comment]
@wuworkshop Thanks! So I got the app running but I still couldn't get the cron job to send emails. I get the following in powershell which means the `emailNotification` in [method.js](https://github.com/codebuddiesdotorg/codebuddies/blob/8fe86898316d47acea274e60ba58a3867cdfd732/server/email/methods.js) is called. 

20161203-06:38:00.009(-8) (percolate_synced-cron.js:71) SyncedCron: Starting "Hangouts Reminder Job".
20161203-06:38:00.020(-8)? found a hangout to send a reminder!
20161203-06:38:00.025(-8)? time diff 23
20161203-06:38:00.024(-8) (percolate_synced-cron.js:71) SyncedCron: Finished "Hangouts Reminder Job".

I have changed the time interval to "every 1 min" but still no emails. Also I tried to console.log() in [method.js](https://github.com/codebuddiesdotorg/codebuddies/blob/8fe86898316d47acea274e60ba58a3867cdfd732/server/email/methods.js) but didn't get any output.

I am working on Windows 10 machine. Meteor version 1.3.2.4.

**Comment by sergeant-q** [comment]
@lpatmo didn't we already fix this in the recent release? I swore someone had addressed this issue already.

**Comment by lpatmo** [comment]
@sergeant-q Nope, this is a different issue. :P Or rather, both logos were broken, but the last issue that was fixed addressed the cancellation email, I think, and this one addresses the reminder email.

@anish-shekhawat Are you not getting the reminder emails after you've created new hangouts that occur between 24-48 hours in the future? Will take a look soon.

**Comment by anish-shekhawat** [comment]
@lpatmo Since my email was not authorized with the mailgun sandbox account, I had to create a mailgun sandbox account separately and use that instead. I have fixed the issue and will be submitting a pull request. 

![image](https://cloud.githubusercontent.com/assets/23295486/20868082/73085c42-ba07-11e6-955b-cc66dd2f2294.png)

Well, as a beginner, I think it would be helpful if the mailgun sandbox instructions are mentioned in [contributing.md](https://github.com/codebuddiesdotorg/codebuddies/blob/master/contributing.md)

Also, this is going to be my first PR. So thanks a lot for letting me help! Let me know if I could be of any help in some other (beginner friendly :P) issue.

**Comment by lpatmo** [comment]
@anish-shekhawat Ahh, I didn't realize that a mailgun sandbox account had to be created in order for the reminder emails to be sent! Thanks for solving the problem!

**Comment by wuworkshop** [comment]
@lpatmo 
uh... shouldn't all the email templates just reference the `logo` key that was modified in this PR https://github.com/codebuddiesdotorg/codebuddies/pull/241/files#diff-641fec1802230bc6359cf3d92b8d47d9

The image path just needs to be updated, no?

**Comment by lpatmo** [comment]
@wuworkshop Yeah, I think you're right. I asked about it in the PR: https://github.com/codebuddiesdotorg/codebuddies/pull/434

**Comment by anish-shekhawat** [comment]
@wuworkshop I was about to do the same thing but since this is my first PR, I checked the alert template [file] (https://github.com/codebuddiesdotorg/codebuddies/blob/master/private/email-hangout-alerts.html#L581) for guidance and the src was pointing to the URL and not the {logo} parameter. Also, when I started working on it, the image src was pointing to the {logo} parameter which was causing the issue. Anyway, I will change this in the next couple of days if its okay with you guys. Do you also want me to change it in the alert template?

**Comment by sergeant-q** [comment]
@anish-shekhawat thank you for working on this issue by the way! A couple of things to note about this functionality:

 - The image src should be referenced by the `{{logo}}` template variable.  This is the right way to do this.
 - The image src URL resolves to the server's absolute URL + path to the image (/images/logo.svg)
 - While testing locally, your server's path will more than likely be `http://localhost/`. 
 - This results in a full image path of `http://localhost/images/logo.svg`.  When the email is fired off, it will try to reference that path and as it will fail because that is not a valid path on the internet.
 - Normally, In order to properly testing this functionality I typically deploy to cloud9 server or some other staging server that is publicly available

I hope that make sense.  So in conclusion, let's continue to use the `{{logo}}` template variable and ensure it is being used in both email templates.  Let me know if you have any questions.

@wuworkshop @lpatmo for visibility.

**Comment by anish-shekhawat** [comment]
@sergeant-q Thanks! I will try deploying it to some publicly available server and will change the reference in both the templates.

**Comment by sergeant-q** [comment]
@anish-shekhawat how are we looking here? Did you make the appropriate updates and test on a publicly available server?

**Comment by anish-shekhawat** [comment]
@sergeant-q I am really sorry I didn't give any update. I had a vacation so I was traveling for the past one month. Before leaving I actually tried to test it on cloud9 server but couldn't because their free tier has only 2 GB storage which was insufficient for the app to run. I also tried to run it on Codeanywhere server but bumped into a lot of issues on their server. Is there any other public staging server that I can test the app on apart from these two?

**Comment by distalx** [comment]
Hey  @anish-shekhawat Thanks for taking this issue.

`Meteor.absoluteUrl` returns an absolute URL. 
We are using it to inject an image to our email template, checkout [here](https://github.com/codebuddiesdotorg/codebuddies/blob/master/server/email/methods.js#L17) 
on production this will return `http://codebuddies.org/images/logo.svg`
on local it will return `http://localhost:3000/images/logo.svg`
Since we are using `HTTPS ` on production we also have to generate a `HTTPS` URL.
By passing an optional parameter `secure:true` we can achieve that.
i.e. `Meteor.absoluteUrl('images/logo.svg', {secure:true});`

Hope this helps!

cc @sergeant-q

**Comment by anish-shekhawat** [comment]
Hi @distalx Thanks for the info.

Is there a way I can test this on a staging server available online? As previously mentioned I have tried CodeAnywhere and Cloud9's free tier but couldn't deploy it on them.

**Comment by distalx** [comment]
@anish-shekhawat  we do have a staging site setup at heroku, how about once you update you branch with the changes, we will deploy it to staging site for testing ?

**Comment by anish-shekhawat** [comment]
Hey, @distalx I just setup an Amazon AWS EC2 instance and got the app running. But I can't seem to make the slack authorization work because after authorizing it goes back to localhost:3000 instead of the AWS public IP.

**Comment by anish-shekhawat** [comment]
@distalx I updated my branch with the required changes.

cc @sergeant-q

**Comment by wuworkshop** [comment]
@anish-shekhawat I think there needs to be one more change to fix the logo in all the email templates. In the file @distalx mentioned (https://github.com/codebuddiesdotorg/codebuddies/blob/master/server/email/methods.js#L17), could you change the logo image from `logo.svg` to `logo-circle.png`?

According to this comment from @lpatmo in this PR https://github.com/codebuddiesdotorg/codebuddies/pull/341#issuecomment-254038017, SVG might not be well supported in a lot of mail templates.

**Comment by lpatmo** [comment]
Good call, @wuworkshop!

**Comment by anish-shekhawat** [comment]
@wuworkshop Done!
