### ISSUE TITLE
Change "Browse" link in top nav to "Browse Hangouts"

### ISSUE THREAD

**Issue by wuworkshop** [codebuddiesdotorg/codebuddies#437]
It appears that the wording "Browse" isn't clear to some people when they initially go to Codebuddies.org. To make it more obvious, it would be good to change it to "Browse Hangouts".

**Comment by Grimmaldi** [comment]
I'd like to work on this issue.  But, instead of changing the label to "Browse Hangouts, can I just change it to "Hangouts"?  I think it reduces clutter, and, since it's in the navbar, shouldn't confuse anyone.

**Comment by wuworkshop** [comment]
@Grimmaldi It's all yours. I just added the "claimed" label. I think your suggestion to use "Hangouts" instead is a good idea. Go for it. 👍

**Comment by Grimmaldi** [comment]
@wuworkshop Thanks for changing the label, and for the words of encouragement.  I've reviewed the file structure of the site, updated the navbar-related HTML, and then commited the change through Git.  It seemed okay...  But, this is my first attempt at anything like this, and, unfortunately, my understanding of Git isn't so hot.  Did it register properly?  Did I update the right section?  If not, I'll go back to my HTML book and/or my Git PDF, and try to get this working.

**Comment by lpatmo** [comment]
@Grimmaldi Thanks for tackling this! A couple of notes:
- Did you go through the steps on contributing.md and fire up an instance of the app in your localhost:3000? I would encourage that you test to see what happens with your changes. 
- In this meteor app, we're using the i18n package, which lets us create a "dictionary" of reusable keys and values (aka "translations"). The i18n/en.i18n.json file contains a list of keywords that we're using, and in the HTML when we have something that looks like `{{_ "browse"}}`, it actually means "go into the en.i18n.json file and look for the corresponding value/translation." So on line 113 of en.i18n.json, you'll see: `  "browse" : "Browse"`. And if you replace "browse" inside those brackets and the underscore with another keyword, that keyword will first have to be defined in en.i18n.json. 

Hope this helps, but let me know if any of this doesn't make sense!

**Comment by Grimmaldi** [comment]
Hi @lpatmo , Okay, I've tested out the app on my localhost:3000, and tested out the changes on my test version of the Code Buddies app.  I didn't previously know about the i18n json file, but, with your gentle nudge, I've made the necessary changes and committed it through my fork of the site.  Please let me know if I've misunderstood something or need to tweak something else.  (And thank you for your patience!)

**Comment by lpatmo** [comment]
@Grimmaldi Thanks for running it in localhost; I looked in your fork, and that change looks great! Maybe to minimize confusion we could check if the "browse" key in the i18n.json is used anywhere else (you can grep or [ag](https://github.com/ggreer/the_silver_searcher) for it, and get a returned list of files where that keyword appears in the codebase) -- and if it's *not* used anywhere else, change the key to something more matching with its value. But in general, not a big deal at all. 

And apologies for not raising up this question before -- but now I'm wondering if the text shouldn't say "Upcoming" or "Live" instead of "Hangouts" or "Browse." Am saying this because the list of all hangouts is already on the home page, and when you click on the "Browse" (or now "Hangouts") link on the nav, you're technically taken to the "Live and Upcoming Hangouts" page, not a page that shows all the hangouts. Unfortunately "Live and Upcoming" is a bit long, but I'm worried that "Hangouts" will be confusing since you're already seeing on the hangouts from the home page. 

@wuworkshop, any thoughts, since you'd originally thought it should be changed to "Browse"?

**Comment by wuworkshop** [comment]
@lpatmo uh, I originally thought it should say "Browse Hangouts". The link already says "Browse". ^^ 

The list of all hangouts only shows up on the homepage when the user logs in to their Slack account. So perhaps the "Hangouts" link should only be visible for people who are NOT logged in. The original purpose of the link was so people who aren't Slack members yet could see what kind of hangouts we have coming up without having to join Slack, right?

**Comment by lpatmo** [comment]
@wuworkshop Ah sorry, I misremembered the original suggestion. 

> So perhaps the "Hangouts" link should only be visible for people who are NOT logged in. The original purpose of the link was so people who aren't Slack members yet could see what kind of hangouts we have coming up without having to join Slack, right?

Yep! I'm down with this idea. So we'll need to wrap the link with something like `{{#unless currentUser}} ... {{/unless}}` (used elsewhere in home.html already; this means "if not currentUser, aka if not logged in"). 

Anyone disagree?

**Comment by Grimmaldi** [comment]
@lpatmo @wuworkshop I have tried to apply the changes that you mentioned above.  Please let me know if I have missed or misunderstood something.  Thanks for walking me through this and for your patience.

**Comment by lpatmo** [comment]
@Grimmaldi Looks great! Want to go ahead and submit a PR for this issue? You just click a button, and select your branch where you pushed your commits. :)

**Comment by Grimmaldi** [comment]
Okay, done...  That was my very first PR submission!  Thank you so much @lpatmo and @wuworkshop !!!!
