### ISSUE TITLE
Tips and Tricks for Study Group Leaders Info Page

### ISSUE THREAD

**Issue by BethanyG** [codebuddiesdotorg/codebuddies#715]
We need an info page/post/guide for Study Group organizers about what they can do to get up and running.  Practical things like:

Making sure you have a Short but attractive description for people to read.
Having clear and well-labeled resources and links
Making a private Slack channel, and setting a good purpose for it
Inviting and welcoming new members when they join the Study Group and the Slack channel.
Establishing a rhythm, and capturing learnings and notes 
Other support resources that are available in Jitsi (like youtube streaming)
Other ways CodeBuddies and leaders can help with your group or your goals

**Comment by kvie** [comment]
I think this is a good start! I think this information should be provided in a couple of places so that people can easily understand what the study groups are intended for, and how to be a member and a leader of a study group, though some thought should be given to how much participation we would ideally like to ask of members and owners each.

I'd like to see a description of study groups on the study group page. A short explanation of what they are for and what users are to expect, encouraging participation in a group rather than just "joining to express interest" and so on.

I'd also like to see a description of tips and expectations for people who intend to start a study group, and I believe a good place for this would be at the top of the form for actually creating the study group.

After a user has created a study group, they should have easy access to tips on how to help the study group succeed. After a user has joined a study group, they should have easy access on how to participate and contribute to the study group.

So there's kind of this divide of information, that easily fits into four categories for me: expectations before vs tips after; owners vs members. I may be overanalyzing, but I just think the info should be doled out as its needed. :)

**Comment by lpatmo** [comment]
Thank you for filing this issue, @BethanyG, and thanks for your thoughts, @Kvie! I started writing up a draft called `Guide for Study Group Owners` at https://docs.google.com/document/d/1Vk4IewieuHEdwrfwo3TvsS3OEpw5dVDEx7ZFUUtlKLE/edit#. Feel free to comment/edit as you desire.

Maybe after this draft is finalized, I will file separate/new issues to:
1) put the content of the study group owners' guide as a page on codebuddies.org/study-group-owners-guide, or something. (Suggestions welcome.)
2) Link to it from each study group page itself, so that group owners can have a quick reference to it. 
3) Fire off an email notification to the study group creator as soon as they've created a study group, that contains the contents of this guide.
4) Invite all study group owners to a Slack channel called #study-group-owners or something in case organizers want to discuss meta strategies and different techniques of learnings. Or at least mention this channel in the guide as a place for organizers to meet.

**Comment by BethanyG** [comment]
Just went through the doc and made edits....but as always, would love if someone else took a look.  Thank you for making the Doc, Linda!

**Comment by lpatmo** [comment]
Thank you so much for expanding on the sections, @BethanyG! 

I am going to paste the contents here and leave it up for a few days; if anyone else lurking on this thread has feedback/comments, please leave a comment in the google doc! After we agree that this is final, I will create two new Github issues: 
- one to task a contributor to create a new page containing this guide, and 
- another that has an email notification firing off to the study group owner whenever anyone creates a study group.

========
Hello there! Congratulations on creating a study group on CodeBuddies.org!
**As the study group owner, please make sure you tick off the following:**

- [ ] Have a short but attractive description for people to read on your group homepage. Clearly define what you want the goal of the study group to be. (Master X? Finish reading Y?).  Having good explanations will help potential members decide if your group fits their goal.

- [ ] Please note that the goal doesn’t have to be grandiose; the best goals are achievable because they’re small and specific!

- [ ] Make sure to add some topic-relevant links in the `Links` tab on your StudyGroup details page.  Label each clearly! Encourage your group members to pin links here, too.  Sharing diverse content helps start discussions and accelerates everyone’s learning.

- [ ] Create a private channel on the CodeBuddies Slack (or request that a public one be created in #codebuddies-meta), and set a good purpose for it. (If you’re short on ideas, feel free to set the purpose to be the URL of your study group.).  

- [ ] Invite and welcome new members when they join the study group and your Slack channel.  Get them as excited as you are about the topic!

- [ ] Decide whether you want to allow all study group members to schedule hangouts - or only the moderators and admins to schedule hangouts.  This is completely up to you.  Do this by selecting [Settings] tab on your StudyGroup details page.
 
- [ ] Remind / poke group members to set their current status in the [Members] tab on the StudyGroup details page.  Having even a small note about what they’re studying or what they’re working on keeps everyone accountable to their goals.

**Tips for making your study group succeed**
1) A study group is a study group as long as there is at least one other member interested in joining. Don’t worry about trying to get a lot of members; the important thing is that you accomplish the goal you set out to do by creating the study group. It’d be ideal if lots of other people who were interested in the same goal as you could connect with you.  But the point here is to mutually motivate one another - no matter how many people there are.   

2) Sometimes you’ll have to DM to encourage your study partners, or post in the Slack channel to keep the study subject or scheduled hangouts fresh in their minds.  Remember:  you are not ‘bothering’ people.  Everyone gets busy and distracted!  Participants often need (and welcome) reminders that they’ve agreed to take part in your group. 

3) If you’re feeling discouraged about the traction your study group is getting, reach out to the community.  Post in the #general channel about your group, have an Admin make a post in #announcements, or start up a discussion in relevant channel(s).

4) Writing down group accomplishments / learnings will help solidify them in memory and create a great record of what the group has achieved together.  It’ll also keep members accountable to their personal goals.  Be proud of coming together to collaborate!

## Introduction on page (not sure if this should go on the email too):
**Why Study Groups?**
We create study groups as motivation to accomplish common learning goals.  We learn better  together.  A study group is a study group as long as there is at least one other member interested in joining.  Ideally, lots of people who are interested in the same topic would come together and learn.  But our point here is to mutually motivate one another - no matter how many people there are learning.  We want to hold ourselves accountable to our learning goals both small and large.

========

**Comment by angelocordon** [comment]
I'd also merit that this is an excellent resource to post on our Medium blog and reference it as a link within the app

**Comment by lpatmo** [comment]
After we create the page (/study-group-owners-guide, maybe?) we could link to this page from the study groups' page too.
