### ISSUE TITLE
"Must be logged in to create StudyGroup"

### ISSUE THREAD

**Issue by nalbina** [codebuddiesdotorg/codebuddies#732]
I feel like this is a huge bummer when I already thought out my studygroup title, description and tags only to see that message when I try to create a study group. Maybe we should blank out the possibility to do that entirely while logged out or prompt them to login.

**Comment by railsstudent** [comment]
Hide the button unless user is logged in?

**Comment by nalbina** [comment]
I think I would lean towards having a greyed out button, so that the user still knows that he can create study groups but on hover gets something like. `You need to be signed in` or smth.

**Comment by railsstudent** [comment]
@nalbina It is feasible but requires some CSS work and logic to check whether user is logged
Initially the "start a study group" button is disabled.  
I am not sure whether this will work.  In OnRendered of all study group,  add event handlers to jQuery hover() to  add title attribute "You need to be signed" when mouse enters the button and the person is not logged in. Similarly, the title attribute is removed when mouse leaves the button

In client side, Meteor.userId() returns user id if user is logged in, null/undefined (I am not sure) otherwise. 
The tough part is how to monitor value change of Meteor.userId() after user sign in and automatically enable the button. I don't know how the slack signin works, maybe we can listen to some event and update the dom

@lpatmo @distalx Please kindly advise.

**Comment by angelocordon** [comment]
Why not follow the same pattern as hangouts where a modal forces you to sign in first before creating anything - 

![image](https://user-images.githubusercontent.com/3891869/33111649-113d5374-cf04-11e7-997f-b780a59433b9.png)

**Comment by angelocordon** [comment]
The authentication pattern should probably be consistent across the board anyways.
