### ISSUE TITLE
Creating an Accomplished Page

### ISSUE THREAD

**Issue by oliikit** [codebuddiesdotorg/codebuddies#86]
We have 'what am I learning' section, but can we create a page where people can post what they've recently accomplished (like our show and tell channel)?

**Comment by adachiu** [comment]
That information (list of accomplishments) would be on each user's dashboard. Users can see other people's dash as well.

**Comment by foxiae** [comment]
Oh, okay. I didn't notice. Would it be possible to have an 'accomplished feed' then? So whenever someone completes a project, the community can see it (or at least it gets announced to the community)? That way, it may open the dialogue of "hey I just finished this project - would anyone mind critiquing the code?"

**Comment by lpatmo** [comment]
I think we roll can this into the "learnings/accomplishments" tab (we've been referring it to so far as the "learnings" tab only, so it might've been confusingly thought as just a "what did I learn" section). 

One idea: we can add a star or a checkbox next to each learning/accomplishment, and let users star which of their learnings/accomplishments they want to publish in the weekly shout-outs newsletter (which I kinda delayed because it was a lot of manual work putting it together, but I want to bring it back).

**Comment by lpatmo** [comment]
I think we can roll this onto our Discourse forum (a "show and tell" thread, where other folks can leave feedback/comments/encouragement) instead of storing it on the hangouts site or on Slack.
